name: Docker Image CI

on:
  push:
    branches: [ "feature/test*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Hello world
      run: |
        echo "Hello World ${{ secrets.DEMO_DEV }}" ; ls -la ; pwd ; echo ${{ secrets.DEMO_DEV }} > test.txt ; cat test.txt
